/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type CommentId = bigint;
export interface CommentView {
  'id' : CommentId,
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
  'replyCount' : bigint,
  'parentId' : [] | [CommentId],
  'postId' : PostId,
}
export type ConversationId = bigint;
export interface ConversationView {
  'id' : ConversationId,
  'lastMessageAt' : [] | [bigint],
  'lastMessage' : [] | [string],
  'otherUser' : Principal,
  'unreadCount' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export type FeedFilter = { 'following' : null } |
  { 'forYou' : null };
export interface FeedPage {
  'posts' : Array<PostView>,
  'nextCursor' : [] | [PostId],
}
export type MessageId = bigint;
export interface MessageView {
  'id' : MessageId,
  'createdAt' : bigint,
  'text' : string,
  'sender' : Principal,
}
export type PlaylistId = bigint;
export interface PlaylistView {
  'id' : PlaylistId,
  'name' : string,
  'createdAt' : bigint,
  'trackIds' : Array<PostId>,
}
export type PostId = bigint;
export interface PostView {
  'id' : PostId,
  'title' : string,
  'likeCount' : bigint,
  'audio' : ExternalBlob,
  'repostCount' : bigint,
  'createdAt' : bigint,
  'repostedByCaller' : boolean,
  'playCount' : bigint,
  'filename' : string,
  'caption' : string,
  'uploader' : Principal,
  'likedByCaller' : boolean,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface UserProfile {
  'principal' : Principal,
  'isFollowing' : boolean,
  'followerCount' : bigint,
  'followingCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'addTrackToPlaylist' : ActorMethod<[PlaylistId, PostId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPlaylist' : ActorMethod<[string], PlaylistId>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentCount' : ActorMethod<[PostId], bigint>,
  'getComments' : ActorMethod<[PostId], Array<CommentView>>,
  'getConversation' : ActorMethod<[ConversationId], [] | [Array<MessageView>]>,
  'getConversations' : ActorMethod<[], Array<ConversationView>>,
  'getFeed' : ActorMethod<[FeedFilter, [] | [PostId], bigint], FeedPage>,
  'getPlaylists' : ActorMethod<[Principal], Array<PlaylistView>>,
  'getPost' : ActorMethod<[PostId], [] | [PostView]>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getRecommendations' : ActorMethod<[bigint], Array<PostView>>,
  'getUserPosts' : ActorMethod<[Principal], Array<PostView>>,
  'getUserReposts' : ActorMethod<[Principal], Array<PostView>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'markConversationRead' : ActorMethod<[ConversationId], undefined>,
  'recordPlay' : ActorMethod<[PostId], undefined>,
  'replyToComment' : ActorMethod<[PostId, CommentId, string], CommentId>,
  'repostPost' : ActorMethod<[PostId], undefined>,
  'schema' : ActorMethod<[], string>,
  'sendMessage' : ActorMethod<[ConversationId, string], MessageId>,
  'startConversation' : ActorMethod<[Principal], ConversationId>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
  'unrepostPost' : ActorMethod<[PostId], undefined>,
  'uploadPost' : ActorMethod<[string, string, ExternalBlob, string], PostId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];