/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const PlaylistId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const CommentView = IDL.Record({
  'id' : CommentId,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'replyCount' : IDL.Nat,
  'parentId' : IDL.Opt(CommentId),
  'postId' : PostId,
});
export const ConversationId = IDL.Nat;
export const MessageId = IDL.Nat;
export const MessageView = IDL.Record({
  'id' : MessageId,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'sender' : IDL.Principal,
});
export const ConversationView = IDL.Record({
  'id' : ConversationId,
  'lastMessageAt' : IDL.Opt(IDL.Int),
  'lastMessage' : IDL.Opt(IDL.Text),
  'otherUser' : IDL.Principal,
  'unreadCount' : IDL.Nat,
});
export const FeedFilter = IDL.Variant({
  'following' : IDL.Null,
  'forYou' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostView = IDL.Record({
  'id' : PostId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'audio' : ExternalBlob,
  'repostCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'repostedByCaller' : IDL.Bool,
  'playCount' : IDL.Nat,
  'filename' : IDL.Text,
  'caption' : IDL.Text,
  'uploader' : IDL.Principal,
  'likedByCaller' : IDL.Bool,
});
export const FeedPage = IDL.Record({
  'posts' : IDL.Vec(PostView),
  'nextCursor' : IDL.Opt(PostId),
});
export const PlaylistView = IDL.Record({
  'id' : PlaylistId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'trackIds' : IDL.Vec(PostId),
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'isFollowing' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'addTrackToPlaylist' : IDL.Func([PlaylistId, PostId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [PlaylistId], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
  'getComments' : IDL.Func([PostId], [IDL.Vec(CommentView)], ['query']),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(IDL.Vec(MessageView))],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationView)], ['query']),
  'getFeed' : IDL.Func(
      [FeedFilter, IDL.Opt(PostId), IDL.Nat],
      [FeedPage],
      ['query'],
    ),
  'getPlaylists' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PlaylistView)],
      ['query'],
    ),
  'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getRecommendations' : IDL.Func([IDL.Nat], [IDL.Vec(PostView)], ['query']),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(PostView)], ['query']),
  'getUserReposts' : IDL.Func([IDL.Principal], [IDL.Vec(PostView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'markConversationRead' : IDL.Func([ConversationId], [], []),
  'recordPlay' : IDL.Func([PostId], [], []),
  'replyToComment' : IDL.Func([PostId, CommentId, IDL.Text], [CommentId], []),
  'repostPost' : IDL.Func([PostId], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [MessageId], []),
  'startConversation' : IDL.Func([IDL.Principal], [ConversationId], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([PostId], [], []),
  'unrepostPost' : IDL.Func([PostId], [], []),
  'uploadPost' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [PostId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const PlaylistId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const CommentView = IDL.Record({
    'id' : CommentId,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'replyCount' : IDL.Nat,
    'parentId' : IDL.Opt(CommentId),
    'postId' : PostId,
  });
  const ConversationId = IDL.Nat;
  const MessageId = IDL.Nat;
  const MessageView = IDL.Record({
    'id' : MessageId,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'sender' : IDL.Principal,
  });
  const ConversationView = IDL.Record({
    'id' : ConversationId,
    'lastMessageAt' : IDL.Opt(IDL.Int),
    'lastMessage' : IDL.Opt(IDL.Text),
    'otherUser' : IDL.Principal,
    'unreadCount' : IDL.Nat,
  });
  const FeedFilter = IDL.Variant({
    'following' : IDL.Null,
    'forYou' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostView = IDL.Record({
    'id' : PostId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'audio' : ExternalBlob,
    'repostCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'repostedByCaller' : IDL.Bool,
    'playCount' : IDL.Nat,
    'filename' : IDL.Text,
    'caption' : IDL.Text,
    'uploader' : IDL.Principal,
    'likedByCaller' : IDL.Bool,
  });
  const FeedPage = IDL.Record({
    'posts' : IDL.Vec(PostView),
    'nextCursor' : IDL.Opt(PostId),
  });
  const PlaylistView = IDL.Record({
    'id' : PlaylistId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'trackIds' : IDL.Vec(PostId),
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'isFollowing' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'addTrackToPlaylist' : IDL.Func([PlaylistId, PostId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [PlaylistId], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
    'getComments' : IDL.Func([PostId], [IDL.Vec(CommentView)], ['query']),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(IDL.Vec(MessageView))],
        ['query'],
      ),
    'getConversations' : IDL.Func([], [IDL.Vec(ConversationView)], ['query']),
    'getFeed' : IDL.Func(
        [FeedFilter, IDL.Opt(PostId), IDL.Nat],
        [FeedPage],
        ['query'],
      ),
    'getPlaylists' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PlaylistView)],
        ['query'],
      ),
    'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getRecommendations' : IDL.Func([IDL.Nat], [IDL.Vec(PostView)], ['query']),
    'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(PostView)], ['query']),
    'getUserReposts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'markConversationRead' : IDL.Func([ConversationId], [], []),
    'recordPlay' : IDL.Func([PostId], [], []),
    'replyToComment' : IDL.Func([PostId, CommentId, IDL.Text], [CommentId], []),
    'repostPost' : IDL.Func([PostId], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [MessageId], []),
    'startConversation' : IDL.Func([IDL.Principal], [ConversationId], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([PostId], [], []),
    'unrepostPost' : IDL.Func([PostId], [], []),
    'uploadPost' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [PostId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };